### ISSUE TITLE
a problem about salientdetect

### ISSUE THREAD

**Issue by lucasliunju** [shunsukeaihara/salientdetect#1]
Hi!
I am very sorry for disturbing you! I am learning saliency region detect. And I found your code in github. When I downloaded the python code,I find I can‘t install it(python setup.py install ,and pip install salientdetect).I try some ways to solve it but it can't solve the problem.So I want to know your operating environment.
Thanks!

**Comment by yhfwww** [comment]
https://www.lfd.uci.edu/~gohlke/pythonlibs/#salientdetect
